spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/product-swagger/**
          filters:
            - StripPrefix=0

        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/auth/**,/api/diary/**,/api/recommendations/**,/api/ai/**,/recommendation-swagger/**
          filters:
            - StripPrefix=0