spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info