spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

product:
  data:
    json-path: /data/FoodData_Central_foundation_food_json_2025-12-18.json